// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../functions/_generated/api.js";

import type { InferInsertModel, InferSelectModel } from "better-convex/orm";
import type { tables } from "../functions/schema";

export const api = {
  database: {
    getMany: createApiLeaf<"query", typeof import("../functions/database").getMany>(convexApi["database"]["getMany"], { auth: "required", type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/database").getOne>(convexApi["database"]["getOne"], { auth: "required", type: "query" }),
    initial: createApiLeaf<"mutation", typeof import("../functions/database").initial>(convexApi["database"]["initial"], { auth: "required", type: "mutation" }),
  },
  organization: {
    accept: createApiLeaf<"mutation", typeof import("../functions/organization").accept>(convexApi["organization"]["accept"], { auth: "required", type: "mutation" }),
    addMember: createApiLeaf<"mutation", typeof import("../functions/organization").addMember>(convexApi["organization"]["addMember"], { auth: "required", rateLimit: "organization/addMember", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/organization").create>(convexApi["organization"]["create"], { auth: "required", rateLimit: "organization/create", type: "mutation" }),
    findOne: createApiLeaf<"query", typeof import("../functions/organization").findOne>(convexApi["organization"]["findOne"], { type: "query" }),
    generateLink: createApiLeaf<"mutation", typeof import("../functions/organization").generateLink>(convexApi["organization"]["generateLink"], { auth: "required", type: "mutation" }),
    getMany: createApiLeaf<"query", typeof import("../functions/organization").getMany>(convexApi["organization"]["getMany"], { auth: "required", type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/organization").getOne>(convexApi["organization"]["getOne"], { auth: "required", type: "query" }),
    invite: createApiLeaf<"mutation", typeof import("../functions/organization").invite>(convexApi["organization"]["invite"], { auth: "required", type: "mutation" }),
    join: createApiLeaf<"mutation", typeof import("../functions/organization").join>(convexApi["organization"]["join"], { auth: "required", type: "mutation" }),
    reject: createApiLeaf<"mutation", typeof import("../functions/organization").reject>(convexApi["organization"]["reject"], { auth: "required", type: "mutation" }),
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
