// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../functions/_generated/api.js";

import type { InferInsertModel, InferSelectModel } from "better-convex/orm";
import type { tables } from "../functions/schema";

export const api = {
  organization: {
    create: createApiLeaf<"mutation", typeof import("../functions/organization").create>(convexApi["organization"]["create"], { auth: "required", rateLimit: "organization/create", type: "mutation" }),
    findOne: createApiLeaf<"query", typeof import("../functions/organization").findOne>(convexApi["organization"]["findOne"], { type: "query" }),
    getOne: createApiLeaf<"query", typeof import("../functions/organization").getOne>(convexApi["organization"]["getOne"], { auth: "required", type: "query" }),
  },
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
