export enum DialogType {
  ACCOUNT = "ACCOUNT",
  PREFERENCES = "PREFERENCES",
  NOTIFICATIONS = "NOTIFICATIONS",
  CONNECTIONS = "CONNECTIONS",
  GENERAL = "GENERAL",
  PEOPLE = "PEOPLE",
  IMPORT = "IMPORT",
  PUBLIC_PAGES = "PUBLIC_PAGES",
  EMOJI = "EMOJI",
  INTEGRATIONS = "INTEGRATIONS",
  TEAMSPACES = "TEAMSPACES",
  BILLING = "BILLING",
}